### ISSUE TITLE
Merge with alfresco-jscript-extensions?

### ISSUE THREAD

**Issue by jgoldhammer** [ciber/alfresco-js-batch-executer#4]
Hi,

I have just seen your cool batch executer project. I am just providing a simple batch processing in the project alfresco-jscript-extensions. Do you think it is a good idea to merge our two projects into one project? That would keep things easier...

The alfresco-jscript-extensions projects tries to provide some useful javascript root objects for developers:
https://github.com/jgoldhammer/alfresco-jscript-extensions

Thanks,
Jens

**Comment by jgoldhammer** [comment]
No reaction.

**Comment by byaminov** [comment]
@jgoldhammer oops, forgot to answer! 

I'm glad you like my batch executer! I also saw your Alfresco JS extensions project, and I think it is indeed a good idea to merge our projects. The end users could use then one project to get all tools needed.

So do you need any help to incorporate this repository into yours? It is a usual Maven Alfresco plugin project, with tests etc.

Regards,
Bulat
