### ISSUE TITLE
large repositories and number of batches

### ISSUE THREAD

**Issue by jservajean** [ciber/alfresco-js-batch-executer#5]
Hi all,
Honestly, I haven't tried out this module, but was wandering a couple of things before I do : 
what happens if the number of documents you are traversing is greater than batchNumber * threadNumber and/or system properties such as solr.query.maximumResultsFromUnlimitedQuery (or max permission checks) ? does the bacth processes only the, says, 800 first nodes found, or does it automatcally creates a new batch ?
Thanks

**Comment by byaminov** [comment]
Hi @jservajean,

> what happens if the number of documents you are traversing is greater than `batchSize * threadsNumber`?

The amount of nodes is split into batches and then fed to all the threads available. Each thread processes one batch at a time. So suppose you have `batch1`, `batch2` and `batch3`. If there is only one thread, then it first processes `batch1`, then `batch2`, then `batch3`. So you don't have any parallelism, but you still have transactions. If e.g. `batch2` would fail, the work done in `batch1` would still be saved into Alfresco.

If for example there are two threads, then `thread1` processes `batch1`, and at the same time `thread2` processes `batch2`. The first thread to finish its batch would take the `batch3` and process it.

> what happens if the number of documents you are traversing is greater than system properties such as `solr.query.maximumResultsFromUnlimitedQuery` or max permission checks?

It depends on which one of these usage types you apply:

    batchExecuter.processFolderRecursively({
        root: companyhome,
        onNode: function(node) {..}
    });

or 

    batchExecuter.processArray({
        items: search.query("some query"),
        onNode: function(row) {..}
    });

In the first situation the batch executer will traverse the whole tree recursively by executing `getChildren()` call for each parent node. So the max permission checks would only be a problem if one parent has more children than "max permission checks".

In the second situation there will be only one search request executed: the `search.query("some query")`. So then it might happen that not all nodes would be returned if the amount of hits is more than "max permission checks".

**Comment by jservajean** [comment]
thanks @byaminov !
